### PR TITLE
This fixes my screwup where I forgot to return the index

### PR DESCRIPTION
**Pull request by chuggafan**
Yhea... I should stop being so jumpy about PRs, I had believed I had done the BSR and BSF intrinsics correctly but I had forgotten that I still needed to return a value in the pointer index passed in... oops.... Sorry about that.

This does bring up a good thing though: there needs to be some easy way to add individual files (rather than projects) for regression testing, the current method is really difficult for doing it. I tried to add some tests when I first made my PR but gave up because it requires, like, 3 different files per file to test.

I also take full blame for this screw-up of mine, I had forgotten about testing THAT SPECIFIC section of the _BitScanForward and _BitScanReverse functions.

### CODE REVIEW

**Comment by LADSoft** [comment]
we could add a test project with a makefile that iterates all the C files in the project directory, building them and running them?   Then we could just throw a file in that directory and be sure the tests in it would run.   That would work for simple tests...   for something that would need several files to do a proper test we could later add some kind of support for subdirectories and more automatic building and running...

**Comment by chuggafan** [comment]
That sounds great. I'll add builtin tests once we have that, that way we can have regression tests that are linked to certain issue numbers and manually add them ourselves, I know of quite a few regressions tests we could therefore add... hmm...

**Comment by LADSoft** [comment]
i added orangec\tests\regression.   For each test you need to add two files, a c or cpp or asm file and a cmpx file.   The cmpx file will be compared against the output of running the created executable (and may be empty).   There are a couple of files that I already added :)

**Comment by GitMensch** [comment]
I still recommend to change the current "manual" regression tests to an autoconf generated testsuite.

You just change the test source ".at" (one single file, or more if you want to group those test sources) and run `make check` to let the testscript be created and run (you can run the testsuite script directly, too).

Possible cons: Needs a shell and diff to run, but those are available in Travis by default and in Appveyor (with its installed MSYS+Cygwin environments) and on a developer machine by WSL additionally. There also exists a java based runner that directly process the tests from the source files.
This approach otherwise needs autoconf to let the testsuite be generated (but autoconf is available in the given environments, too)

pro:
* developer just adds/adjust the test source file
* checks stdout, stderr and return code (all these can be ignored if wanted)
* a test can consist of as much files as you want, both source files and "expected" files [normally a diff to stdout/stderr is enough]
* creates a nice test result log for each single test run and also for the complete testsuite
* single tests may be run with passing a keyword, those are taken from the test title and can additionally be specified
* failing tests can easily be re-run after the tested binaries where updated - or after the test sources where adjusted

I offer to create a PR which changes the regression tests to use autoconf generated testscript, *if* both @chuggafan and @LADSoft are open to use something that won't work in plain win32-only environments directly [but even for this case the java based test runner should work fine].

Opinions?

**Comment by LADSoft** [comment]
my main comment is that as it stands, the programs will not run except on windows.    While they compile on travis, there is no possibility they would work properly if run on travis.   While this could be addressed we keep pushing back #227...    I suppose we've proved the programs would work on mingw though?   And the other thing is we've got issue #255 to move this to azure at some point in the future, would this solution work ok on that platform as well?

**Comment by GitMensch** [comment]
Yes, Travis CI originally had no win32 support , "back then" [Tea CI](https://tea-ci.org) was a similar option that supported win32.
But since October [Travis CI added Win32 environment](https://blog.travis-ci.com/2018-10-11-windows-early-release) so it should be possible to use this one to additionally compile on Win32 *and* run autoconf based tests. See #257 for a request to add this environment with a travis multiple os configuration.

**Comment by GitMensch** [comment]
> While they compile on travis, there is no possibility they would work properly if run on travis. While this could be addressed [...]

Is this a "we should have an issue to support GNU/Linux environments"? If it doesn't exists yet I'm all for creating this one, even if it is low-priority (currently there are only 34 open issues that are not related to ocide so another one doesn't harm).

**Pull request merged**
