### PR TITLE
Add FNV functions and more customization in error lists

### PR DESCRIPTION
**Pull request by chuggafan**
This PR adds the FNV functions to a namespace called "Util" (because Utils is taken by a class instead of a namespace), I also added a few support things to do GCC warning compat along with help text for some warnings.

As for actually getting the frontend to do this... I don't know enough about the utilities used for processing the input flags to modify them to accept this stuff.

### CODE REVIEW

**Comment by chuggafan** [comment]
Adding a comment to link in #610 that this is related to but doesn't completely solve, but this should mostly fix that. This also does some work (towards the naming) for #605

**Comment by LADSoft** [comment]
Sorry for the delay, I been on vacation lol.   I was thinking, we could turn 'utils' into a namespace.    I *think* that might be ok because everything in 'utils' should be static anyway.   It is probably just a matter of refactoring the header file...

**Comment by LADSoft** [comment]
as far as the error processing, it would just be a matter of instantiating a CmdSwitchxxxxx class (which you could do with new).   Once the class is instantiated everything else is automagic, the first argument to the class constructor hooks it into the switch mechanisms.    But of course you have to do that before calling the switchparser...

**Comment by chuggafan** [comment]
I'm going to use the already existing Werror=whatever thing and begin to use the stuff I've made.

**Comment by LADSoft** [comment]
were you needing some guidance on this?

**Comment by chuggafan** [comment]
I did a bunch of the work so far, just been lazy about committing atm cuz I have a lot of work this week

**Comment by chuggafan** [comment]
Got back around to doing some testing on my changes, since I'm very busy these next few weeks I'll be unable to do much development, since my changes are having issues (but I think I can still add what I want), I wouldn't want the pull merged immediately once I commit my current work because it doesn't... work.

**Comment by LADSoft** [comment]
are you ready to have this merged?

**Comment by chuggafan** [comment]
No, the actual feature doesn't work and I've had a lot of other stuff on my mind, so I haven't had the time, if you want to figure out why 1. This decreases the compile speed enough to put us over the 1:30 mark and/or 2. why this change is not working it'd be fine... but I have no idea what's wrong with it atm and I likely won't have the time this week or next week to figure it out.

**Comment by chuggafan** [comment]
Got around to testing just now, turns out the issue was really, really, reallllllllllllly simple and easy to overlook: miss-spelled a macro.

**Comment by GitMensch** [comment]
If I understood that correctly it is ready to be merged in (so stays in and possibly is updated), but will need a later follow-up PR to be finished. Correct? If this is a WIP-PR please mark it that way.

**Comment by chuggafan** [comment]
Technically everything that is needed for this is completed, the only things that need to be added/fixed-up are having help menu stuffs, but I'm not sure we want that and it can go into its own PR block. As-is this is perfectly fine for accomplishing what *I* want re: getting less errors when doing the libcxx tests.

**Comment by LADSoft** [comment]
It looks like it probably won't mess with the build times appreciably, are you ready for me to review and merge it into the main line?

**Comment by chuggafan** [comment]
Absolutely, only things to work on would be theoretical help stuff but that would likely require a rewrite of the help section itself even further to get it to a nice area.

**Comment by chuggafan** [comment]
Made a few fixups so the analyzer stops compllaining.

**Comment by LADSoft** [comment]
I was about to look at merging this...   but apparently the build is failing in a big way right now.    It was ok the other day except for the debug build which timed out as usual...

**Comment by chuggafan** [comment]
Ye, the issue was that I wanted to apply [[noreturn]] on some functions, but OCC is unique in erroring on it if a noreturn function has a return value, I'm debating whether this should be downgraded to a warning or I should work around it.

Pros for downgrading to a warning:
- Allows marking the contract of a function being used as a function pointer, like in this case.
Cons for downgrading to a warning:
- Suspiciously marked noreturn functions are strange

**Comment by chuggafan** [comment]
I've decided to do a temp workaround for this [[noreturn]] error as a demonstration that other than that everything is good, leaving the conundrum above to be shoved aside for later consideration (I should probably make an issue so we can further discuss this outside of a pull request, but I have other stuff I'm doing today....)

As for other stuff such as me moving to VS2022: meh, seems ok to do so since it still supports the VS2019 toolset, only problem could be that VS2022 is IIRC supposed to get an ABI break via vNext on the microsoft STL but other people would know far more than me about that...

**Comment by chuggafan** [comment]
Gonna be honest and say that I am consistently forgetting the small things with these changes somehow... so I'll probably squash the past ~5ish commits into one then force push sometime later tonight because I should have more time to think then

**Comment by LADSoft** [comment]
thanks... will make it slightly easier to review.   I'll make an issue so we don't forget the [[noreturn]] problem

**Comment by chuggafan** [comment]
Got around to it just now, so all the relevant analyzer fixes are squashed

**Pull request merged**
