### PR TITLE
Build Orange C on Cygwin

### PR DESCRIPTION
**Pull request by iahunq**
https://github.com/LADSoft/OrangeC/issues/916

### CODE REVIEW

**Comment by chuggafan** [comment]
Why would you close this?

**Comment by iahunq** [comment]
> Why would you close this?

Because I don't know how to fix this:

```
$ ./occparse
unknown (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023

Usage: unknown [options] [@response file] files
```

Normally, it should be like this:

```
occparse (OrangeC) Version 6.0.70.2
Copyright (C) LADSoft 2006-2023

Usage: occparse [options] [@response file] files
```

**Comment by LADSoft** [comment]
yeah there are a bunch of issues actually running code that is built with GCC.    It is a known issue (#278) that while it compiles ok at this point, there are some incompatibilities.   I was thinking of moving that up and trying to correct them now I've fixed it so it compiles in msys2...

**Comment by iahunq** [comment]
Btw, compiling fine and working are very different things. With this hack I managed to have Orange C compiled on Cygwin. But I found various places on the source code have `__linux__` defined. Cygwin is definitely not Linux so there will be definitely compatibility issues. Finally this is just a hacking for fun project of mine when waiting for you to fix the `omake` crashing problems.

**Comment by LADSoft** [comment]
yeah I got rid of the __linux__ definitions last night lol...

the goal with compiling for linux has to date been that it would compile, without regard for functionality :smile:

**Pull request closed without merging**
