### PR TITLE
Fixes constant expression variables outside of functions

### PR DESCRIPTION
**Pull request by chuggafan**
This is for #243 and seems to work fine, all I did was set constexpr variables to const, as they are implicitly const, https://en.cppreference.com/w/cpp/language/constexpr

### CODE REVIEW

**Comment by LADSoft** [comment]
it looks like the CI failure is some glitch with appveyor, if you agree I will merge this request.

**Comment by GitMensch** [comment]
Whatever caused this, the changes in the sources cannot be taken responsible that the CLANG environment misses a path (this *may* be a timing and parallel build issue though).

**Comment by chuggafan** [comment]
Looks like GitMensch is right in regards to why AppVeyor failed here: the CLANG build environment seems to have failed at cd'ing to the project directory. I don't know if you think this PR solves the issue it purports or not, if you believe it does than I think it's fine to accept it.

**Comment by LADSoft** [comment]
I didn't realize until after I merged this that the error still needed to happen if the constant's expression was not a constant.   I'm going to go ahead and fix it...

**Pull request merged**
