### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by GabrielRavier**
I use imgbot, a bot that automatically compresses images in a git repo. The compression is lossless, and should thus only contribute to making the repository smaller.

### CODE REVIEW

**Comment by GabrielRavier** [comment]
Yeah gonna try to check if any of these images aren't test images and can actually be safely optimized.

**Comment by LADSoft** [comment]
FWIW the tests are in \orangec\tests; some of the tests might work on images.   a lot of the other stuff you touched goes in the IDE help file which I'm just assuming would work :)

**Comment by LADSoft** [comment]
this needs to build before I can accept it...

**Comment by LADSoft** [comment]
rejected because it broke the build

**Pull request closed without merging**
