### PR TITLE
Fix occ crashing with a pair of functions

### PR DESCRIPTION
**Pull request by chuggafan**
OCC crashes at https://github.com/LADSoft/OrangeC/blob/60fcd108fc530b1db25d02af0ee4f1e351d76348/src/occ/parse/declcons.cpp#L1712-L1714 when funcparams->sp is null, this is what is causing the crash with #366 I've fixed the crashing by just having PromoteConstructorArgs exit immediately if funcparams->sp is null, however, in #366 's case it should not be null, and I should investigate more as to why OCC isn't recognizing that the function's overload/constructor exists in this case... I think it's something to do with std::forward, but who knows...

### CODE REVIEW

**Comment by chuggafan** [comment]
Adding in issue #370 to this PR because both related heavily to crashing and honestly it's much easier to work on this that way...

**Comment by LADSoft** [comment]
I merged it because I wasn't able to duplicate the build problems; I'll leave it open since you are still working on #370 though.

**Comment by LADSoft** [comment]
that was a good thing using std::stack.   I hadn't used it enough for it to be on my radar so I might have done something a little more drastic :)

**Comment by chuggafan** [comment]
Yhea, std::stack and std::vector are my two favorite STL containers because of their simplicity and usefulness.

My only problem with std::stack is that there's no command to both take the top of the stack and pop the stack after getting it.

**Pull request merged**
