### PR TITLE
Add some more 64 bit intrinsics

### PR DESCRIPTION
**Pull request by chuggafan**
Name is on the tin, I looked into how MSVC implemented _rotr64 and _rotl64 and did just that, if any calling convention problems come up that's something that we need to fix because I did just a dump of the ASM from MSVC (the optimized version, ofc) and then used that, with fastcall calling convention...

### CODE REVIEW

**Comment by chuggafan** [comment]
So APPARENTLY the compiler is trying to generate ```shrd eax, edx, cx``` when I'm trying to do ```shrd eax, edx, cl``` and that I'm using the same register size as ```mov cl, bl```

**Comment by LADSoft** [comment]
yeah i'm not sure what is going on with that.   I will try to figure it out tomorrow...

**Comment by LADSoft** [comment]
i fixed the SHLD/SHRD thing on the main line....

**Comment by chuggafan** [comment]
*Sigh* I did some work on this today, I ran into some weird issues that I have no clue why they're being the way they are...

So on MY COMPUTER I did this to the _rotr generation function:


```cpp

    AMODE* eax = makedreg(EAX);
    AMODE* edx = makedreg(EDX);
    AMODE* ecx = makedreg(ECX);
    AMODE* ebx = makedreg(EBX);
    AMODE* esi = makedreg(ESI);
    /*
    MSVC does ROTR64 AND ROTL64 as:
    unsigned __int64 rotr(unsigned __int64,int) PROC                             ; rotr, COMDAT
        mov     edx, DWORD PTR _num$[esp]
        push    ebx
        mov     ebx, ecx
        push    esi
        mov     esi, DWORD PTR _num$[esp+4]
        test    bl, 32                              ; 00000020H
        je      SHORT $LN3@rotr
        mov     eax, esi
        mov     esi, edx
        mov     edx, eax
$LN3@rotr:
        mov     eax, esi
        and     bl, 31                                    ; 0000001fH
        je      SHORT $LN4@rotr
        mov     cl, bl
        shrd    eax, edx, cl
        shrd    edx, esi, cl
$LN4@rotr:
        pop     esi
        pop     ebx
        ret     8

        The only diff is between shrd and shld
        */
    // Rotate it around for the parameters so that we match above, I'm too lazy to make this effecient atm ~ chugga_fan

    gen_code(op_mov, eax, edx);
    gen_code(op_mov, edx, ecx);
    gen_code(op_mov, ecx, eax);
    gen_code(op_xor, eax, eax);

    gen_code(op_mov, edx, ecx);
    gen_code(op_push, ebx, nullptr);
    gen_code(op_mov, ebx, ecx);
    gen_code(op_push, esi, nullptr);
    gen_code(op_mov, esi, edx);
    ebx->length = ISZ_UCHAR;
    gen_code(op_test, ebx, aimmed(32));
    int lab = beGetLabel;
    gen_branch(op_je, lab);
    gen_code(op_mov, eax, esi);
    gen_code(op_mov, esi, edx);
    gen_code(op_mov, edx, eax);
    ecx->length = ISZ_UCHAR;
    oa_gen_label(lab);
    int lab1 = beGetLabel;
    gen_code(op_mov, eax, esi);
    gen_code(op_and, ebx, aimmed(31));
    gen_branch(op_je, lab1);
    ecx->length = ISZ_UCHAR;
    gen_code(op_mov, ecx, ebx);
    auto op = right ? op_shrd : op_shld;
    gen_code3(op, eax, edx, ecx);
    gen_code3(op, edx, esi, ecx);
    oa_gen_label(lab1);
    ebx->length = ISZ_UINT;
    gen_code(op_pop, esi, nullptr);
    gen_code(op_pop, ebx, nullptr);

```


for some reason these four lines:

```cpp
   gen_code(op_mov, eax, edx);
    gen_code(op_mov, edx, ecx);
    gen_code(op_mov, ecx, eax);
    gen_code(op_xor, eax, eax);

```

generate these four instructions:

```asm

	mov	eax,ebx ; WHY THE ?!?!?
	mov	edx,ecx
	mov	ecx,eax
	xor	eax,eax

```

Why does EBX exist here?!?!

I generated this code from:

```c
#include <stdio.h>
int main()
{
    printf("%lld\n", _rotr64(12, 2));
}
```

I literally cannot understand why ebx is referenced when I clearly referenced EDX there. Something in the codegen is being unhelpful and I don't understand *WHY*

**Comment by LADSoft** [comment]
it may be a bug or it may be the designed behavior...   what may be happening is the long long constant is being put into EBX:ECX register pair.   Then the compiler does generate the code to move from EBX to EDX (as required by the intrinsic) but eventually realizes the registers hold the same value and optimizes your instruction to directly use EBX instead of doing the intermediate move.  If you want you can try compiling with /O- /P- to see what it generates...   /P- tells it not to do the final peephole optimizations which will give you a closer view as to what the compiler is originally generating...

if that isn't it I will look at it tonite...

**Comment by chuggafan** [comment]
I tried what you said:

```asm
push	byte 02h
	mov	eax,0ch
	mov	edx,00h
	push	edx
	push	eax
	mov	eax,edx
	mov	edx,ecx
	mov	ecx,eax
	xor	eax,eax
	mov	edx,ecx
	push	ebx
	mov	ebx,ecx
	push	esi
	mov	esi,edx
	test	bl,020h
	je	short	L_8
	mov	eax,esi
	mov	esi,edx
	mov	edx,eax
L_8:
	mov	eax,esi
	and	bl,byte 01fh
	je	short	L_9
	mov	cl,bl
	shrd	eax,edx,cl
	shrd	edx,esi,cl
L_9:
	pop	esi
	pop	ebx
	add	esp,byte 0ch
	mov	eax,eax
	mov	edx,edx
	push	edx
	push	eax
	push	dword L_1
	call	_printf
	add	esp,byte 0ch
; Line 5:	}
	mov	eax,00h
L_3:
	ret

```

That broke it even more, seems optimized + no peephole = no idea wtf fastcall is, as it is pushing parameters on the stack as if it were _cdecl calling convention.... 

```asm

	push	byte 02h
	mov	eax,0ch
	xor	edx,edx
	push	edx
	push	eax
	mov	eax,edx
	mov	edx,ecx
	mov	ecx,eax
	xor	eax,eax
	mov	edx,ecx
	push	ebx
	mov	ebx,ecx
	push	esi
	mov	esi,edx
	test	bl,020h
	je	short	L_8
	mov	eax,esi
	mov	esi,edx
	mov	edx,eax
L_8:
	mov	eax,esi
	and	bl,byte 01fh
	je	short	L_9
	mov	cl,bl
	shrd	eax,edx,cl
	shrd	edx,esi,cl
L_9:
	pop	esi
	pop	ebx
	add	esp,byte 0ch
	push	edx
	push	eax
	push	dword L_1
	call	_printf
	add	esp,byte 0ch
; Line 5:	}
	xor	eax,eax
L_3:
	ret

```

and that is just /O-, seems similarly bad.

**Comment by LADSoft** [comment]
these four lines:

    gen_code(op_mov, eax, edx);
    gen_code(op_mov, edx, ecx);
    gen_code(op_mov, ecx, eax);
    gen_code(op_xor, eax, eax);

seem wrong.   I think you need a temp reg to cache the original contents of eax before you move something into it (or alternately creative use of xchg).    I tried a simplified version of that and it seemed to generate correct code...

I am looking into the other issues now...

**Comment by LADSoft** [comment]
ok the other issue is that /O- doesn't handle fastcall properly.  /P- does seem to work properly as long as you don't combine it with /O- though.

I think it an easy fix but don't want to touch it until #348 clears (hopefully tomorrow).   Do you mind writing an issue?

**Comment by chuggafan** [comment]
*Sigh* so the hasher I found on stackoverflow has this small problem where it uses constexpr evaluation in templates, meaning I'd have to platform define the size of that hasher rather than let constexpr evaluation do it because the compiler can't do that, other than that, for some reason __builtin_clz with this hash function isn't being found? I'll investigate this more later.

**Comment by LADSoft** [comment]
sounds like #298 is getting in the way now?  I've been meaning to fix it but keep getting derailed...

**Comment by chuggafan** [comment]
#298 is getting in the way of the new hash-function so that I can use an unordered_map with const char* as a key, so it's a minor "in-the-way" instead of the main reason, but it's still an annoyance, yes...

**Comment by GitMensch** [comment]
@chuggafan Just out of interest (mostly in seeing this PR be merged and closed) - do you have any update on this? The last (failing) build was from April.

**Comment by chuggafan** [comment]
I literally haven't touched this PR since it was last updated, one of the things I have been working on for fixing this PR is #368 which is just the tip of the iceberg of the problems that I need to fix. I've been trying to investigate why it's happening, and I'll get somewhere further on this later.

**Pull request closed without merging**
